namespace:
  name: staging 
 
service:
  port: 5111
  type: ClusterIP

image:
  repository: nginx 
  tag: 1.18.0
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits: 
    cpu: 128Mi
    memory: 500m
